version: "3"

vars:
  PREFIX: "{{.HOME}}/.local/opt"
  MODULE_SYNTAX: "lua" # or "tcl"
  MODULE_PREFIX: "{{.PREFIX}}/modulefiles/lammps"
  CATEGORY: "stable"

tasks:
  default:
    desc: "Alias of all"
    cmds:
      - task: all

  all:
    desc: "Build/install all configured LAMMPS targets and generate modulefiles"
    cmds:
      - for:
          matrix:
            DATE: ["22Jul2025_update5"]
        task: target
        vars: { CATEGORY: "stable", DATE: "{{.ITEM.DATE}}" }

  target:
    desc: "Build/install one LAMMPS target and generate a modulefile"
    requires: { vars: [CATEGORY, DATE] }

    cmds:
      - task: install_lammps
        vars:
          CATEGORY: "{{.CATEGORY}}"
          DATE: "{{.DATE}}"
          PREFIX: "{{.PREFIX}}"
      - task: generate_modulefile
        vars:
          CATEGORY: "{{.CATEGORY}}"
          DATE: "{{.DATE}}"
          PREFIX: "{{.PREFIX}}"

  install_lammps:
    desc: "Build/install LAMMPS after loading configured modules"
    requires: { vars: [CATEGORY, DATE] }
    sources:
      - "{{.TASKFILE_DIR}}/Taskfile.lammps.yml"
    generates:
      - "{{.PREFIX}}/lammps/{{.CATEGORY}}_{{.DATE}}/bin/lmp"
    vars:
      LMP_PREFIX: "{{.PREFIX}}/lammps/{{.CATEGORY}}_{{.DATE}}"
    cmds:
      - cmd: |
          MODULE_CONFIG_FILE=$("{{.TASKFILE_DIR}}/scripts/resolve-file.sh" "{{.TASKFILE_DIR}}/config/modules.txt")
          source "{{.TASKFILE_DIR}}/scripts/modules.sh"
          module-load ${MODULE_CONFIG_FILE}
          export PYTHON_VERSION="$({{.TASKFILE_DIR}}/scripts/get-python-version.sh)"
          task --taskfile "{{.TASKFILE_DIR}}/Taskfile.lammps.yml" all \
            CATEGORY="{{.CATEGORY}}" \
            DATE="{{.DATE}}" \
            PREFIX="{{.LMP_PREFIX}}"

  generate_modulefile:
    desc: "Generate LAMMPS modulefile"
    requires: { vars: [CATEGORY, DATE] }
    vars:
      VERSION: "{{.CATEGORY}}_{{.DATE}}"
      LMP_PREFIX: "{{.PREFIX}}/lammps/{{.VERSION}}"
      MODULE_FILE: "{{.MODULE_PREFIX}}/{{.VERSION}}.{{.MODULE_SYNTAX}}"
      TEMPLATE_FILE:
        sh: |
          OS="$({{.TASKFILE_DIR}}/scripts/get-os.sh)"
          echo "{{.TASKFILE_DIR}}/template/template.${OS}.{{.MODULE_SYNTAX}}"
    sources:
      - "{{.TEMPLATE_FILE}}"
    generates:
      - "{{.MODULE_FILE}}"
    env:
      VERSION: "{{.VERSION}}"
      PREFIX: "{{.LMP_PREFIX}}"
    cmds:
      - cmd: |
          mkdir -p "{{.MODULE_PREFIX}}"
          MODULE_CONFIG_FILE=$("{{.TASKFILE_DIR}}/scripts/resolve-file.sh" "{{.TASKFILE_DIR}}/config/modules.txt")
          source "{{.TASKFILE_DIR}}/scripts/modules.sh"
          module-load ${MODULE_CONFIG_FILE}
          MODULE_DEPENDS_ON="$(module-deps ${MODULE_CONFIG_FILE} {{.MODULE_SYNTAX}})"
          PYTHON_VERSION="$({{.TASKFILE_DIR}}/scripts/get-python-version.sh)"
          export PYTHONPATH="{{.LMP_PREFIX}}/lib/python{{.PYTHON_VERSION}}/site-packages"
          export MODULE_DEPENDS_ON="${MODULE_DEPENDS_ON}"
          envsubst '$VERSION $PREFIX $PYTHONPATH $MODULE_DEPENDS_ON' < "{{.TEMPLATE_FILE}}" > "{{.MODULE_FILE}}"
