version: "3"

vars:
  PREFIX: "{{.HOME}}/.local/opt"
  MODULE_SYNTAX: "tcl" # or "lua"
  MODULE_PREFIX: "{{.PREFIX}}/modulefiles/lammps"
  CATEGORY: "stable"

tasks:
  default:
    desc: "Alias of all"
    cmds:
      - task: all

  all:
    desc: "Build/install all configured LAMMPS targets and generate modulefiles"
    cmds:
      - for:
          matrix:
            DATE: ["22Jul2025_update5"]
        task: target
        vars: { CATEGORY: "stable", DATE: "{{.ITEM.DATE}}" }

  target:
    desc: "Build/install one LAMMPS target and generate a modulefile"
    requires: { vars: [CATEGORY, DATE] }

    cmds:
      - task: install_lammps
        vars:
          CATEGORY: "{{.CATEGORY}}"
          DATE: "{{.DATE}}"
          PREFIX: "{{.PREFIX}}/lammps/{{.CATEGORY}}_{{.DATE}}"
      - task: generate_modulefile
        vars:
          CATEGORY: "{{.CATEGORY}}"
          DATE: "{{.DATE}}"
          PREFIX: "{{.PREFIX}}"

  install_lammps:
    desc: "Build/install LAMMPS after loading configured modules"
    requires: { vars: [CATEGORY, DATE, PREFIX] }
    sources:
      - "{{.TASKFILE_DIR}}/Taskfile.lammps.yml"
    generates:
      - "{{.PREFIX}}/lammps/{{.CATEGORY}}_{{.DATE}}/bin/lmp"
    vars:
      TASKFILE: "{{.TASKFILE_DIR}}/Taskfile.lammps.yml"
      DEPMOD_FILE:
        sh: '"{{.TASKFILE_DIR}}/scripts/resolve-file.sh" "{{.TASKFILE_DIR}}/config/modules.txt"'
    cmds:
      - cmd: |
          source "{{.TASKFILE_DIR}}/scripts/modules.sh"
          module-load {{.DEPMOD_FILE}}
          task --taskfile "{{.TASKFILE}}" all \
            CATEGORY="{{.CATEGORY}}" \
            DATE="{{.DATE}}" \
            PREFIX="{{.PREFIX}}"

  generate_modulefile:
    desc: "Generate LAMMPS modulefile"
    requires: { vars: [CATEGORY, DATE, PREFIX] }
    vars:
      VERSION: "{{.CATEGORY}}_{{.DATE}}"
      MODULE_PREFIX: "{{.PREFIX}}/modulefiles/lammps"
      MODULE_FILE: "{{.MODULE_PREFIX}}/{{.VERSION}}.{{.MODULE_SYNTAX}}"
      DEPMOD_FILE:
        sh: '"{{.TASKFILE_DIR}}/scripts/resolve-file.sh" "{{.TASKFILE_DIR}}/config/modules.txt"'
      TEMPLATE_FILE:
        sh: |
          OS="$({{.TASKFILE_DIR}}/scripts/get-os.sh)"
          echo "{{.TASKFILE_DIR}}/template/template.${OS}.{{.MODULE_SYNTAX}}"
    sources:
      - "{{.TEMPLATE_FILE}}"
    generates:
      - "{{.MODULE_FILE}}"
    env:
      VERSION: "{{.VERSION}}"
      PREFIX: "{{.PREFIX}}/lammps/{{.VERSION}}"
    cmds:
      - cmd: |
          mkdir -p "{{.MODULE_PREFIX}}"
          source "{{.TASKFILE_DIR}}/scripts/modules.sh"
          module-load {{.DEPMOD_FILE}}
          export MODULE_DEPENDS_ON="$(module-deps {{.DEPMOD_FILE}} {{.MODULE_SYNTAX}})"
          export PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
          export MODULE_DEPENDS_ON="${MODULE_DEPENDS_ON}"
          envsubst '$VERSION $PREFIX $PYTHON_VERSION $MODULE_DEPENDS_ON' < "{{.TEMPLATE_FILE}}" > "{{.MODULE_FILE}}"
